### ISSUE TITLE
pcl_surface occur build error with certain Eigen versions

### ISSUE THREAD

**Issue by UnaNancyOwen** [PointCloudLibrary/pcl#1496]
## Build pcl_surface

PCL(pcl_surface) can't build with certain version of Eigen in Visual Studio.
These combination is follows Visual Studio versions and Eigen versions.

PCL(pcl_surface) master/HEAD [e97b664](https://github.com/PointCloudLibrary/pcl/tree/e97b664546b50747df68faaf92837dedf07a3cb7)

<table>
  <tr>
    <td></td>
    <td>Visual Studio 2013 Update5</td>
    <td>Visual Studio 2015 Update1</td>
  </tr>
  <tr>
    <td>Eigen 3.2.6</td>
    <td>success</td>
    <td>failure</td>
  </tr>
  <tr>
    <td>Eigen 3.2.7</td>
    <td>success</td>
    <td><strong>failure</strong></td>
  </tr>
  <tr>
    <td>Eigen 3.3.0 beta1</td>
    <td><strong>failure</strong></td>
    <td>success</td>
  </tr>
    <tr>
    <td>Eigen 3.3.0 dev branch/HEAD (<a href="https://bitbucket.org/eigen/eigen/src/96cd95bf7744ea57773d231741f27543baa7f3c9/?at=default" target="_blank">e97b664</a>) </td>
    <td><strong>failure</strong></td>
    <td>success</td>
  </tr>
</table>

## [Error] Visual Studio 2015 Update1 + Eigen 3.2.7

```
c:\program files\eigen\include\eigen3\eigen\src\core\products\generalmatrixmatrix.h(62): fatal error C1001: INTERNAL COMPILER ERROR
c:\program files\eigen\include\eigen3\eigen\src\core\products\generalmatrixmatrix.h(62): fatal error C1001: INTERNAL COMPILER ERROR
cl : Command line error D8040: error creating or communicating with child process.
```

This error that caused in Eigen.
You can be solved by version up to Eigen 3.3.0.
This case is no problem.
## [Error] Visual Studio 2013 Update5 + Eigen 3.3.0 beta1

```
error C2664: 'Eigen::aligned_allocator<U>::aligned_allocator(const Eigen::aligned_allocator<U> &)' : cannot convert parameter 1 from  'std::allocator<T>' to 'const Eigen::aligned_allocator<U> &'  C:\Program Files\Boost\include\boost-1_59\boost\unordered\detail\allocate.hpp   489
error C2664: 'Eigen::aligned_allocator<U>::aligned_allocator(const Eigen::aligned_allocator<U> &)' : cannot convert parameter 1 from 'std::allocator<T>' to 'const Eigen::aligned_allocator<U> &'   C:\Program Files\Boost\include\boost-1_59\boost\unordered\detail\allocate.hpp   489
error C2664: 'Eigen::aligned_allocator<U>::aligned_allocator(const Eigen::aligned_allocator<U> &)' : cannot convert parameter 1 from 'std::allocator<T>' to 'const Eigen::aligned_allocator<U> &'   C:\Program Files\Boost\include\boost-1_59\boost\unordered\detail\allocate.hpp   489
```

Maybe, I think this error that caused in PCL.
I don’t know the cause of error in this environment (PCL master/HEAD + Eigen 3.3.0 + Visual Studio 2013).

Do you have any ideas?

**Comment by taketwo** [comment]
Can you trace these errors to specific files/lines in PCL?

**Comment by UnaNancyOwen** [comment]
I can't put my finger on it, whether the error is occurred in file/line of source code.
(sorry, lack my knowledge about c++)
However, It seems to be occurring in pcl_surface by look at the <strong>[build log](https://gist.github.com/UnaNancyOwen/711b98da6185022c9a49#file-buildlog-txt)</strong>.
Please check it.

**Comment by taketwo** [comment]
Try to replace [line 96](https://github.com/PointCloudLibrary/pcl/blob/master/surface/include/pcl/surface/grid_projection.h#L96) in "grid_projection.h" with:

```cpp
typedef boost::unordered_map<int, Leaf, boost::hash<int>, std::equal_to<int>, Eigen::aligned_allocator<std::pair<const int, Leaf> > > HashMap;
```

Just yesterday I merged #1497 with a very similar fix.

**Comment by UnaNancyOwen** [comment]
I tried to replace and rebuild pcl_surface, but still occurred the same error.

**Comment by taketwo** [comment]
Please upload the new build log, there must be at least some difference.

**Comment by UnaNancyOwen** [comment]
Please check <strong>[rebuild log](https://gist.github.com/UnaNancyOwen/711b98da6185022c9a49#file-buildlog_02-txt)</strong>.

**Comment by taketwo** [comment]
Hm, no idea. Looks like a very subtle bug raising from interaction between these specific versions of Boost, Eigen, and the compiler. With the change I proposed, it is definitely not a problem on PCL side. By the way, I discovered we had this bug reported already: #1266.

**Comment by UnaNancyOwen** [comment]
I tryed to replace to std::allocator, the build error was not occurred.
But, I can't say whether that is correct or not, because lack my knowledge about c++.

```
typedef boost::unordered_map<int, Leaf, boost::hash<int>, std::equal_to<int>, std::allocator<std::pair<const int, Leaf> > > HashMap;
```

**Comment by UnaNancyOwen** [comment]
> With the change I proposed, it is definitely not a problem on PCL side.

Okay, Thank you for debugging with me.

**Comment by taketwo** [comment]
`std::allocator` is what you get by default anyway (if you don's specify it at all). So what you wrote now is same as just:

```cpp
typedef boost::unordered_map<int, Leaf, boost::hash<int>, std::equal_to<int> > HashMap;
```

Apparently, the intention of the author of `GridProjection` class was to have the `Leaf` objects allocated with alignment. If we drop this as you did, the compilation succeeds, but spurious segfaults may start happen in runtime, as it always happens with misaligned Eigen types. So, this is a way to make the compiler happy, however it potentially introduces bugs.

**Comment by UnaNancyOwen** [comment]
I was understanding that the way is wrong.
For now, I will roll back Eigen 3.2.6 to be used.
Thank you! :)

**Comment by UnaNancyOwen** [comment]
Eigen 3.2.8 has been released.
This verion was confirmed to be able to build PCL(pcl_surface) on both Visual Studio 2013 and 2015.
<table>
  <tr>
    <td></td>
    <td>Visual Studio 2013</td>
    <td>Visual Studio 2015</td>
  </tr>
  <tr>
    <td>Eigen 3.2.7</td>
    <td>success</td>
    <td>failure</td>
  </tr>
  <tr>
    <td>Eigen 3.2.8</td>
    <td><b>success</b></td>
    <td><b>success</b></td>
  </tr>
  <tr>
    <td>Eigen 3.3.0 beta1</td>
    <td>failure</td>
    <td>success</td>
  </tr>
</table>
This issue has been resolved.
Thanks.

**Comment by taketwo** [comment]
Which version do you plan to ship with pre-built 1.8.0?

**Comment by UnaNancyOwen** [comment]
@taketwo Yes, I will create All-in-one Installer when PCL 1.8.0 was released.
If possible, I want to distribute it in the PCL official web.

**Comment by SergioRAgostinho** [comment]
Website is broken (read-only) at the moment. The issue will be addressed in upcoming hackfest, with a lot of luck, sooner.

**Comment by photoniker** [comment]
We tried to built PCL with VS2013, Boost 1.60.0 and Eigen 3.2.8 and had the same issues than reported from the original author of this issue. Only with Eigen 3.2.7 we didn't get any compiler errors. So we cannot confirm the table (success, failure) listed above.

**Comment by UnaNancyOwen** [comment]
Update Status 
-------------
### Development Environment
* PCL 1.8.0 RC2 (latest release)
* Visual Studio 2015 Update2 (new version)
* CMake 3.5.1 (latest release)

### CMake Configure
* [Test CMake Configure](https://gist.github.com/UnaNancyOwen/c5250181b3985eeb5e79)

### Build Status
**Win32**
<table>
  <tr>
    <td></td>
    <td>VC12 Update5</td>
    <td>VC14 Update2</td>
  </tr>
  <tr>
    <td>Eigen 3.2.7</td>
    <td>success</td>
    <td>success</td>
  </tr>
  <tr>
    <td>Eigen 3.2.8</td>
    <td>success</td>
    <td>success</td>
  </tr>
</table>
**x64**
<table>
  <tr>
    <td></td>
    <td>VC12 Update5</td>
    <td>VC14 Update2</td>
  </tr>
  <tr>
    <td>Eigen 3.2.7</td>
    <td>success</td>
    <td>success</td>
  </tr>
  <tr>
    <td>Eigen 3.2.8</td>
    <td>success</td>
    <td>success</td>
  </tr>
</table>

**Comment by teemu-kemppainen** [comment]
This still fails with 
* VC12 
* Eigen 3.2.9
* Boost 1.61
* PCL from git/master

**Comment by mattbolgercsiro** [comment]
Should this issue be closed given the error still occurs with the latest stable 3.2.9 Eigen release and an actual fix hasn't been identified? I haven't tested with Eigen3.3-beta2 but hit this issue trying to build with the latest Eigen stable. I assume the Boost version doesn't make any difference?

**Comment by SergioRAgostinho** [comment]
Indeed not.

**Comment by chr-thien** [comment]
This still fails with

    VC12 (Visual Studio 2013 Update 5)
    Eigen 3.2.10 or Eigen 3.3.1
    Boost 1.61
    PCL from git/master

`error C2664: 'Eigen::aligned_allocator<U>::aligned_allocator(const Eigen::aligned_allocator<U> &)' : cannot convert argument 1 from 'std::allocator<T>' to 'const Eigen::aligned_allocator<U> &' [pcl_surface.vcxproj]`

**Comment by chr-thien** [comment]
No problem with MSVC14 (Visual Studio 2015 Update 3) and Eigen 3.2.10 or Eigen 3.3.1.

**Comment by UnaNancyOwen** [comment]
I have not tried all combinations, but I think this error is occur by specific versions combination of MSVC, Boost and Eigen.
(e.g. The error will occur Boost 1.61.0, Eigen 3.3.1/3.2.10 with MSVC12.)

I tried the latest versions Boost and Eigen with MSVC12 and MSVC14.
It could be built pcl_surface in all combinations.

* MSVC12 / MSVC14
* PCL master/HEAD (7517d1b)
* Boost 1.63.0
* Eigen 3.3.1 / 3.2.10

I recommend using the latest versions Boost and Eigen.
Thanks,

Note: Please apply this PR #1788 to find Boost 1.63.0 using CMake.

**Comment by kaikai2** [comment]
Eigen's aligned_allocator start to derive from std::allocator in version 3.3.0 which makes boost think it has method select_on_container_copy_construction(). As it doesn't overload the method with return type of itself boost failed to call that method in boost::unordered::detail::allocator_traits::select_on_container_copy_construction() with the compile error above mentioned.
