### ISSUE TITLE
CMake Error occurs in new PCLConfig.cmake

### ISSUE THREAD

**Issue by UnaNancyOwen** [PointCloudLibrary/pcl#2059]
The user own project can't creat using new PCLConfig.cmake, because an error has occurre when congfigure using CMake. 
These options (Ensenso SDK, OpenNI) has been disabled when building PCL.
(<code>WITH_ENSENSO</code> and <code>WITH_OPENNI</code> is OFF.)
Strangely, These options (david SDK, DepthSense SDK, RealSense SDK) has also been disabled when building PCL, but no error occurs for these.
(<code>WITH_DAVIDSDK</code>, <code>WITH_DSSDK</code> and <code>WITH_RSSDK</code> is OFF.)
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ENSENSO_LIBRARY (ADVANCED)
    linked by target "project" in directory c:/sample
OPENNI_LIBRARY (ADVANCED)
    linked by target "project" in directory c:/sample
```
This problem can be fixed temporarily with the following changes in [PCLConfig.cmake#L570](https://github.com/PointCloudLibrary/pcl/blob/master/PCLConfig.cmake.in#L570).
(Remove <code>${OPENNI_LIBRARIES}</code> and <code>${ENSENSO_LIBRARIES}</code>)
But, It is not desirable. :(

```patch
- list(APPEND PCL_LIBRARIES ${BOOST_LIBRARIES} ${QHULL_LIBRARIES} ${OPENNI_LIBRARIES} ${OPENNI2_LIBRARIES} ${ENSENSO_LIBRARIES} ${davidSDK_LIBRARIES} ${DSSDK_LIBRARIES} ${RSSDK_LIBRARIES} ${FLANN_LIBRARIES} ${VTK_LIBRARIES})
+ list(APPEND PCL_LIBRARIES ${BOOST_LIBRARIES} ${QHULL_LIBRARIES} ${OPENNI2_LIBRARIES} ${davidSDK_LIBRARIES} ${DSSDK_LIBRARIES} ${RSSDK_LIBRARIES} ${FLANN_LIBRARIES} ${VTK_LIBRARIES})
```

Do you know anything about this problem?

## Your Environment

* Operating System and version: Windows
* Compiler: Visual Studio
* PCL Version: 1.8.1-dev (master/HEAD)
* CMake version: 3.9.5

**Comment by taketwo** [comment]
The only difference between Ensenso/OpenNI and the other grabbers that I can find are these lines:

https://github.com/PointCloudLibrary/pcl/blob/7b3b5716562bdd55f981ac2803d94cf4b7cb7bad/io/CMakeLists.txt#L371-L379

But this does not offer any hints how to solve the problem. I will need to investigate more.

**Comment by taketwo** [comment]
I checked the `PCLConfig.cmake` file and how it is generated. To be honest, I think it's a big mess and I'm not even sure how to approach cleaning it up.

As for this particular issue, it results from the sloppy way the dependencies are handled. Currently, we try to re-discover and link all optional dependencies, even if they were not found during library build time. And the linking in this config script is less robust than in the main CMakeLists, so we get errors when some of the libraries are not found.

Here is a workaround fix for Ensenso. Instead of improving the dependency handling I just make sure that the finder script does not set variables if the library is not found. Please give this patch a try. If it works, I'll produce similar fixes for OpenNI/OpenNI2 and submit a PR.

[ensenso-patch.txt](https://github.com/PointCloudLibrary/pcl/files/1451606/ensenso-patch.txt)

**Comment by SergioRAgostinho** [comment]
Sorry for all this trouble guys 😅 @taketwo had already warned that #1421 was gonna be a huge problem, but I really believe that now is the best time to clean it up for 1.9.0.

**Comment by taketwo** [comment]
Oh wow, I just re-read my first comment in that thread. There I point to one example of what a potential issue can be: #1337. And guess what, this exact issue just hit us :D

**Comment by UnaNancyOwen** [comment]
@taketwo PCLConfig.cmake will work correctly when applying that patch. CMake Error about Ensenso doesn't occur. Please submit Pull Request. Thanks,

> Currently, we try to re-discover and link all optional dependencies, even if they were not found during library build time.

I think that we should solve this problem in the future.

**Comment by frozar** [comment]
@taketwo After applying the patch, I can pass the cmake configuration step :+1:

**Comment by kgreenek** [comment]
I am still seeing this issue with QHull (using current pcl master). If I don't have QHull installed, I can't have a cmake project that depends on PCL. PCL builds fine, but the config script that PCL installs requires QHull to be installed.

**Comment by taketwo** [comment]
Please file a new issue with all relevant information, error output, etc.

**Comment by kgreenek** [comment]
Done (#2343). Thanks :)
