### ISSUE TITLE
PCLVisualizer updatePointCloud too slow

### ISSUE THREAD

**Issue by zhangzscn** [PointCloudLibrary/pcl#5527]
use the master tree pcl，vtk 9.2。it update the pointcloud too slow，but click the window with the mouse, everything is fine 。code like this：

for .....
        if (viewer.contains("cloud"))
        {
            viewer.updatePointCloud(cloud_temp.makeShared());
        }
        else
        {
            viewer.addPointCloud(cloud_temp.makeShared());
        }

        viewer.resetCamera();
        viewer.spinOnce();

**Comment by larshg** [comment]
Please describe better why you think updatePointCloud is too slow?

Have you measured the time it takes to do updatePointCloud?

Updating the point cloud is not necessarily the same as re-rendering, which would be required if you pan with the camera.

Please show more info if we are to help.

**Comment by zhangzscn** [comment]
Since 1000 depth maps are read and converted into a point cloud for display, the rendering point cloud needs to be updated all the time。
When I comment out the following code, it runs fine, but uncommented, it runs slowly。

ubuntu20.04 i9 13900k rtx4090

if (viewer.contains("cloud"))
{
viewer.updatePointCloud(cloud_temp.makeShared());
}
else
{
viewer.addPointCloud(cloud_temp.makeShared());
}

    viewer.resetCamera();
    viewer.spinOnce();

**Comment by zhangzscn** [comment]
cmake set SSE AVX MARCHNATIVE to OFF
![2022-11-25 15-34-06屏幕截图](https://user-images.githubusercontent.com/13817275/203926726-7d5844a5-a74e-4f62-929b-2a2845cca9fa.png)

**Comment by zhangzscn** [comment]
when i use this code， the close function also crash。
// while (!viewer.wasStopped())
// {
       //     viewer.spinOnce();
// }
// viewer.removeAllPointClouds();
// viewer.removeAllShapes();
        
viewer.close();

**Comment by mvieth** [comment]
@zhangzscn How many points are in your point cloud?
Also note that `makeShared()` (as in `cloud_temp.makeShared()`) makes a copy of the cloud, so this also takes some time. Try to avoid using `makeShared()` if your clouds are large and performance is critical.

**Comment by zhangzscn** [comment]
hi，everyone，the slow method is spinOnce()。76800 points in my pointcloud。 

> @zhangzscn How many points are in your point cloud? Also note that `makeShared()` (as in `cloud_temp.makeShared()`) makes a copy of the cloud, so this also takes some time. Try to avoid using `makeShared()` if your clouds are large and performance is critical.

**Comment by mvieth** [comment]
@zhangzscn Ok, 76800 points is not that much, so that shouldn't be a problem.
Why do you think `spinOnce()` is slow? Did you measure the time it takes?
It also is not clear to me what you are trying to do in general. My guess is that you receive a new point cloud every few milliseconds, and you want the visualizer to display that, like a stream or video of point clouds. Is that right or are you doing something completely different?

**Comment by zhangzscn** [comment]
I have one rgbd camera,so need to update the pointcloud everytime。

**Comment by zhangzscn** [comment]
It usually takes 1S to update the point cloud. However, if you hold down the left mouse button and click the display window, the update speed of the point cloud is normal

**Comment by kangzixiang** [comment]
Any updates? 
I had the same problem.
I use the pcl::HDLGrabber to grab Velodyne lidar data packet(.pcap), Then use the PCLVisualizer to show the point cloud, like  the manual https://pcl.readthedocs.io/projects/tutorials/en/master/hdl_grabber.html#hdl-grabber 
When I use the VTK-7.1 and PCL 1.10, it show's normally the viewer can update everytimes. after i update VTK from 7.1 to 9.2.6, and PCL from 1.10 to 1.13, this problem happened. if you hold down the mouse button or keyboard, the viewer can show's normally.
anyone can help?

**Comment by kangzixiang** [comment]
> 
I fixed this issue by use cloudViewer->spinOnce(1, true) to instead cloudViewer->spinOnce();but i still don't know why this happened.

**Comment by larshg** [comment]
This was an error in VTK, see [here](https://gitlab.kitware.com/vtk/vtk/-/issues/18951). Should be fixed in master VTK if you can try it.

But thanks for posting a alternative, until one can update to a newer VTK release.

**Comment by mvieth** [comment]
I think we can close this issue then, since there is nothing else we can do on the PCL side.

**Comment by wang2673** [comment]
I use cloudViewer->spinOnce(1, true) to instead cloudViewer->spinOnce();but i still don't work ,can you show your code ?
