### ISSUE TITLE
Reading PLY file produces segmentation fault

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#675]
Some PLY files cannot be loaded and the PLYReader produces a segmentation fault.

Test code
---
```cpp
#include <pcl/io/ply_io.h>

int
main (int argc, char *argv[])
{
  if (argc < 2)
    return (-1);

  pcl::PointCloud<pcl::PointXYZRGBA> cloud;

  int rvalue;
  rvalue = pcl::io::loadPLYFile (argv[1], cloud);
  printf ("loadPLYFile = %d\n", rvalue);

  if (rvalue < 0)
  {
    PCL_ERROR ("Could not load file !\n");
    return (-1);
  }

  return (0);
}
```
[Test file](https://mega.co.nz/#!9QE3VLRC!6MxE4uXekdct1b52wK6vvmSU7XtuGlxyW7eaWl5pjNc)

Error
---
```
$ ./ply_segfault 
Segmentation fault (core dumped)
```

It happens only with "special" PLY files. I don't know what causes this bug

**Comment by VictorLamoine** [comment]
I'm fed up with this poor PLY support :rage: 

From what I've debugged so far the seg fault happens in [this loop](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/ply/ply_parser.cpp#L516) when reading the first face.

The code is very dense and hard to debug, if anyone has information I'll be grateful.

**Comment by taketwo** [comment]
Fixed via #1371

**Comment by Datoclement** [comment]
Is this fixed? I find this segfault with macOSX High Sierra 10.13.6 with Python 3.6. I test it with the test file above and it gives a segfault.

**Comment by SergioRAgostinho** [comment]
PCL is still not officially supporting Python bindings. This means you are using custom Python bindings made from another project. It might happen that this project is still wrapping an older version of the library and that is why you're still experiencing this bug.

**Comment by rivertam** [comment]
This seems to still be occurring for me.

My program:

```cpp
#include <pcl/visualization/cloud_viewer.h>
#include <pcl/io/ply_io.h>

int main() {
  pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZRGB>());
  std::cout << "loading" << std::endl;
  pcl::io::loadPLYFile("/home/rivertam/example.ply", *cloud);
  std::cout << "loaded" << std::endl;

  pcl::visualization::CloudViewer viewer("Simple Cloud Viewer");
  viewer.showCloud(cloud);
  while (!viewer.wasStopped()) { }

  return 0;
}


```

and my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.1.0)

project(claudia)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1z -g -pthread -Wall")

find_package(PCL 1.7 REQUIRED COMPONENTS common io visualization)

include_directories(${PCL_INCLUDE_DIRS})

link_directories(${PCL_LIBRARY_DIRS})

add_definitions(${PCL_DEFINITIONS})

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} ${PCL_LIBRARIES} ${PCL_LIBRARY_DIRS})
```

The output is:

```
loading
[1]    31531 segmentation fault (core dumped)  ./claudia
```

**Comment by kunaltyagi** [comment]
The fix was applied to PCL 1.8 and you're using PCL 1.7 (released in 2014) which means either you'll have to backport it yourself or upgrade to a newer version of PCL.
